/**
 * Seed data for initializing the local database.
 * Extracted from server/db.ts to keep the main database module focused.
 */

import { Product, Category, Brand, BannerSlide, NewsArticle, SiteSettings } from '../../src/types/index.js';

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'MÁY CÀY',
    slug: 'may-cay',
    description: 'Các dòng máy cày, máy kéo nông nghiệp công suất lớn',
    imageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a2f?w=500&auto=format&fit=crop&q=80',
    productCount: 12,
    sortOrder: 1,
  },
  {
    id: 'cat-2',
    name: 'MÁY XỚI ĐẤT',
    slug: 'may-xoi-dat',
    description: 'Máy xới đất, máy phay đất đa năng cho vườn và đồng ruộng',
    imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=500&auto=format&fit=crop&q=80',
    productCount: 8,
    sortOrder: 2,
  },
  {
    id: 'cat-3',
    name: 'MÁY GẶT ĐẬP',
    slug: 'may-gat-dap',
    description: 'Máy gặt đập liên hợp thu hoạch lúa năng suất cao',
    imageUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=500&auto=format&fit=crop&q=80',
    productCount: 6,
    sortOrder: 3,
  },
  {
    id: 'cat-4',
    name: 'MÁY BƠM NƯỚC',
    slug: 'may-bom-nuoc',
    description: 'Máy bơm nước động cơ xăng và diesel tưới tiêu nông nghiệp',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=500&auto=format&fit=crop&q=80',
    productCount: 15,
    sortOrder: 4,
  },
  {
    id: 'cat-5',
    name: 'MÁY PHÁT ĐIỆN',
    slug: 'may-phat-dien',
    description: 'Máy phát điện công nghiệp và gia đình hoạt động bền bỉ',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
    productCount: 9,
    sortOrder: 5,
  },
  {
    id: 'cat-6',
    name: 'MÁY CẮT CỎ',
    slug: 'may-cat-co',
    description: 'Máy cắt cỏ đeo vai, máy cắt cỏ đẩy tay chính hãng',
    imageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a2f?w=500&auto=format&fit=crop&q=80',
    productCount: 14,
    sortOrder: 6,
  },
  {
    id: 'cat-7',
    name: 'PHỤ TÙNG',
    slug: 'phu-tung',
    description: 'Phụ tùng thay thế chính hãng cho các dòng máy nông nghiệp',
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500&auto=format&fit=crop&q=80',
    productCount: 45,
    sortOrder: 7,
  },
  {
    id: 'cat-8',
    name: 'PHỤ KIỆN',
    slug: 'phu-kien',
    description: 'Dầu nhớt, phụ kiện bảo dưỡng và thiết bị hỗ trợ nông cơ',
    imageUrl: 'https://images.unsplash.com/photo-1618042164219-62c820f10723?w=500&auto=format&fit=crop&q=80',
    productCount: 28,
    sortOrder: 8,
  },
];

export const SEED_BRANDS: Brand[] = [
  { id: 'brand-1', name: 'John Deere', slug: 'john-deere', country: 'Mỹ', description: 'Thương hiệu máy nông nghiệp hàng đầu thế giới' },
  { id: 'brand-2', name: 'Honda', slug: 'honda', country: 'Nhật Bản', description: 'Động cơ và máy nông cơ bền bỉ số 1 Nhật Bản' },
  { id: 'brand-3', name: 'Kubota', slug: 'kubota', country: 'Nhật Bản', description: 'Giải pháp máy nông nghiệp toàn diện Châu Á' },
  { id: 'brand-4', name: 'Elemax', slug: 'elemax', country: 'Nhật Bản', description: 'Chuyên dòng máy phát điện chất lượng cao' },
  { id: 'brand-5', name: 'Husqvarna', slug: 'husqvarna', country: 'Thụy Điển', description: 'Máy làm vườn và cắt cỏ chuyên nghiệp' },
  { id: 'brand-6', name: 'Yanmar', slug: 'yanmar', country: 'Nhật Bản', description: 'Máy cày và máy gặt liên hợp hiện đại' },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Máy cày John Deere 5055E',
    slug: 'may-cay-john-deere-5055e',
    sku: 'JD-5055E',
    model: '5055E',
    brandId: 'brand-1',
    brandName: 'John Deere',
    categoryId: 'cat-1',
    categoryName: 'MÁY CÀY',
    price: 420000000,
    priceType: 'FIXED',
    currency: 'VND',
    description: 'Máy cày John Deere 5055E công suất 55 HP, trang bị động cơ Turbo 3 xi-lanh mạnh mẽ, tiết kiệm nhiên liệu tối đa.',
    status: 'ACTIVE',
    featured: true,
    isHot: false,
    isNew: false,
    sortOrder: 1,
    images: [
      { id: 'img-1', productId: 'prod-1', url: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a2f?w=800&auto=format&fit=crop&q=80', isPrimary: true, sortOrder: 1 },
    ],
    specifications: [
      { id: 's-1', productId: 'prod-1', key: 'Công suất', value: '55 HP (Mã lực)' },
      { id: 's-2', productId: 'prod-1', key: 'Động cơ', value: 'John Deere PowerTech 3029T' },
      { id: 's-3', productId: 'prod-1', key: 'Dung tích xi-lanh', value: '2.9 Litres' },
      { id: 's-4', productId: 'prod-1', key: 'Hộp số', value: '9 tiến / 3 lùi SyncReverser' },
      { id: 's-5', productId: 'prod-1', key: 'Sức nâng thủy lực', value: '1800 kg' },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Máy xới đất Honda FJ 500',
    slug: 'may-xoi-dat-honda-fj-500',
    sku: 'HD-FJ500',
    model: 'FJ S00',
    brandId: 'brand-2',
    brandName: 'Honda',
    categoryId: 'cat-2',
    categoryName: 'MÁY XỚI ĐẤT',
    price: 18500000,
    priceType: 'FIXED',
    currency: 'VND',
    description: 'Máy xới đất Honda FJ 500 trang bị động cơ GX160 chính hãng. Khả năng xới sâu, làm tơi đất vượt trội cho cây ăn quả và rau màu.',
    status: 'ACTIVE',
    featured: true,
    isHot: true,
    isNew: false,
    sortOrder: 2,
    images: [
      { id: 'img-2', productId: 'prod-2', url: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&auto=format&fit=crop&q=80', isPrimary: true, sortOrder: 1 },
    ],
    specifications: [
      { id: 's-6', productId: 'prod-2', key: 'Động cơ', value: 'Honda GX160 4 thì' },
      { id: 's-7', productId: 'prod-2', key: 'Công suất cực đại', value: '5.5 HP' },
      { id: 's-8', productId: 'prod-2', key: 'Chiều rộng xới', value: '800 mm' },
      { id: 's-9', productId: 'prod-2', key: 'Chiều sâu xới', value: '320 mm' },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Máy gặt Kubota DC-70 Plus',
    slug: 'may-gat-kubota-dc-70-plus',
    sku: 'KB-DC70P',
    model: 'DC-70 Plus',
    brandId: 'brand-3',
    brandName: 'Kubota',
    categoryId: 'cat-3',
    categoryName: 'MÁY GẶT ĐẬP',
    price: 320000000,
    priceType: 'FIXED',
    currency: 'VND',
    description: 'Máy gặt đập liên hợp Kubota DC-70 Plus công suất 70 mã lực, tối ưu khả năng di chuyển trên đồng lúa lầy bơi.',
    status: 'ACTIVE',
    featured: true,
    isHot: false,
    isNew: true,
    sortOrder: 3,
    images: [
      { id: 'img-3', productId: 'prod-3', url: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&auto=format&fit=crop&q=80', isPrimary: true, sortOrder: 1 },
    ],
    specifications: [
      { id: 's-10', productId: 'prod-3', key: 'Công suất', value: '70.8 HP / 2700 rpm' },
      { id: 's-11', productId: 'prod-3', key: 'Chiều rộng hàm cắt', value: '2075 mm' },
      { id: 's-12', productId: 'prod-3', key: 'Dung tích thùng chứa lúa', value: '300 L' },
      { id: 's-13', productId: 'prod-3', key: 'Tốc độ di chuyển', value: '1.85 m/s' },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'Máy bơm nước Honda WB30XT',
    slug: 'may-bom-nuoc-honda-wb30xt',
    sku: 'HD-WB30XT',
    model: 'WB30XT',
    brandId: 'brand-2',
    brandName: 'Honda',
    categoryId: 'cat-4',
    categoryName: 'MÁY BƠM NƯỚC',
    price: 7500000,
    priceType: 'FIXED',
    currency: 'VND',
    description: 'Máy bơm nước Honda WB30XT đường kính ống 80mm (3 inches), lưu lượng bơm tối đa 1100 lít/phút, bền bỉ cực kỳ.',
    status: 'ACTIVE',
    featured: true,
    isHot: false,
    isNew: false,
    sortOrder: 4,
    images: [
      { id: 'img-4', productId: 'prod-4', url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=800&auto=format&fit=crop&q=80', isPrimary: true, sortOrder: 1 },
    ],
    specifications: [
      { id: 's-14', productId: 'prod-4', key: 'Động cơ', value: 'Honda GX160T2' },
      { id: 's-15', productId: 'prod-4', key: 'Đường kính ống hút/xả', value: '80 mm (3 inches)' },
      { id: 's-16', productId: 'prod-4', key: 'Lưu lượng tối đa', value: '1100 L/min' },
      { id: 's-17', productId: 'prod-4', key: 'Cột áp tối đa', value: '23 m' },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: 'Máy phát điện Elemax SH7600EX',
    slug: 'may-phat-dien-elemax-sh7600ex',
    sku: 'EL-SH7600EX',
    model: 'SH7600EX',
    brandId: 'brand-4',
    brandName: 'Elemax',
    categoryId: 'cat-5',
    categoryName: 'MÁY PHÁT ĐIỆN',
    price: 19800000,
    priceType: 'FIXED',
    currency: 'VND',
    description: 'Máy phát điện Elemax SH7600EX công suất cực đại 6.5 kVA, động cơ Honda GX390 Nhật Bản, trang bị đề điện tiện lợi.',
    status: 'ACTIVE',
    featured: true,
    isHot: false,
    isNew: false,
    sortOrder: 5,
    images: [
      { id: 'img-5', productId: 'prod-5', url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80', isPrimary: true, sortOrder: 1 },
    ],
    specifications: [
      { id: 's-18', productId: 'prod-5', key: 'Công suất liên tục', value: '5.6 kVA' },
      { id: 's-19', productId: 'prod-5', key: 'Công suất tối đa', value: '6.5 kVA' },
      { id: 's-20', productId: 'prod-5', key: 'Động cơ', value: 'Honda GX390 (Nhật Bản)' },
      { id: 's-21', productId: 'prod-5', key: 'Dung tích bình xăng', value: '28 Litres' },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    name: 'Máy cắt cỏ Husqvarna 143R-II',
    slug: 'may-cat-co-husqvarna-143r-ii',
    sku: 'HQ-143R2',
    model: '143R-II',
    brandId: 'brand-5',
    brandName: 'Husqvarna',
    categoryId: 'cat-6',
    categoryName: 'MÁY CẮT CỎ',
    price: 6200000,
    priceType: 'FIXED',
    currency: 'VND',
    description: 'Máy cắt cỏ đeo vai Husqvarna 143R-II Thụy Điển động cơ 2 thì mạnh mẽ 41.5cc, chuyên dùng phát cỏ đồi rừng và đồng ruộng.',
    status: 'ACTIVE',
    featured: true,
    isHot: false,
    isNew: false,
    sortOrder: 6,
    images: [
      { id: 'img-6', productId: 'prod-6', url: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a2f?w=800&auto=format&fit=crop&q=80', isPrimary: true, sortOrder: 1 },
    ],
    specifications: [
      { id: 's-22', productId: 'prod-6', key: 'Dung tích xilanh', value: '41.5 cm³' },
      { id: 's-23', productId: 'prod-6', key: 'Công suất', value: '1.5 kW / 2.01 HP' },
      { id: 's-24', productId: 'prod-6', key: 'Trọng lượng khô', value: '7.6 kg' },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    name: 'Máy cày Yanmar YM357A',
    slug: 'may-cay-yanmar-ym357a',
    sku: 'YM-357A',
    model: 'YM357A',
    brandId: 'brand-6',
    brandName: 'Yanmar',
    categoryId: 'cat-1',
    categoryName: 'MÁY CÀY',
    price: 385000000,
    priceType: 'FIXED',
    currency: 'VND',
    description: 'Máy cày Yanmar YM357A công suất 57 HP, trang bị hệ thống định vị GPS thông minh và động cơ TNV tiết kiệm dầu.',
    status: 'ACTIVE',
    featured: false,
    isHot: true,
    isNew: true,
    sortOrder: 7,
    images: [
      { id: 'img-7', productId: 'prod-7', url: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a2f?w=800&auto=format&fit=crop&q=80', isPrimary: true, sortOrder: 1 },
    ],
    specifications: [
      { id: 's-25', productId: 'prod-7', key: 'Công suất', value: '57 HP' },
      { id: 's-26', productId: 'prod-7', key: 'Động cơ', value: 'Yanmar 4TNV98' },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-8',
    name: 'Bộ bánh răng hộp số máy cày John Deere',
    slug: 'bo-banh-rang-hop-so-may-cay-john-deere',
    sku: 'PT-JD-GEAR',
    model: 'GEAR-5055',
    brandId: 'brand-1',
    brandName: 'John Deere',
    categoryId: 'cat-7',
    categoryName: 'PHỤ TÙNG',
    price: 1850000,
    priceType: 'FIXED',
    currency: 'VND',
    description: 'Phụ tùng bộ bánh răng hộp số chính hãng John Deere đúc từ thép hợp kim gia nhiệt siêu chịu lực.',
    status: 'ACTIVE',
    featured: false,
    isHot: false,
    isNew: false,
    sortOrder: 8,
    images: [
      { id: 'img-8', productId: 'prod-8', url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80', isPrimary: true, sortOrder: 1 },
    ],
    specifications: [
      { id: 's-27', productId: 'prod-8', key: 'Chất liệu', value: 'Thép hợp kim tôi cứng' },
      { id: 's-28', productId: 'prod-8', key: 'Tương thích', value: 'Series 5045E, 5055E, 5075E' },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_BANNERS: BannerSlide[] = [
  {
    id: 'ban-1',
    titleLine1: 'GIẢI PHÁP TOÀN DIỆN',
    titleLine2: 'CHO NÔNG NGHIỆP HIỆN ĐẠI',
    description: 'Cung cấp đa dạng các dòng máy nông nghiệp chất lượng cao, đáp ứng mọi nhu cầu sản xuất nông nghiệp.',
    bgImageUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1600&auto=format&fit=crop&q=80',
    machineImageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a2f?w=1000&auto=format&fit=crop&q=80',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'ban-2',
    titleLine1: 'ĐÔI MỚI CÔNG NGHỆ',
    titleLine2: 'NÂNG CAO NĂNG SUẤT NÔNG SẢN',
    description: 'Hệ thống máy gặt đập, máy xới đất và thiết bị nông cơ thế hệ mới chính hãng 100%.',
    bgImageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1600&auto=format&fit=crop&q=80',
    machineImageUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1000&auto=format&fit=crop&q=80',
    sortOrder: 2,
    isActive: true,
  },
];

export const SEED_NEWS: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'Kinh nghiệm chọn máy cày phù hợp với nhu cầu canh tác đồng ruộng',
    slug: 'kinh-nghiem-chon-may-cay-phu-hop',
    summary: 'Hướng dẫn lựa chọn công suất máy cày, loại lốp và dàn xới tối ưu cho từng vùng đất phù sa hay đất đồi.',
    content: 'Đồng ruộng Việt Nam có địa hình đa dạng. Bài viết giúp bà con nông dân lựa chọn dòng máy cày từ 35HP đến 75HP đúng chuẩn...',
    imageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a2f?w=600&auto=format&fit=crop&q=80',
    publishedAt: '2026-05-20',
    views: 1240,
  },
  {
    id: 'news-2',
    title: 'Bảo dưỡng máy nông nghiệp đúng cách giúp tăng tuổi thọ gấp 2 lần',
    slug: 'bao-duong-may-nong-nghiep-dung-cach',
    summary: 'Quy trình thay nhớt, vệ sinh lọc gió, kiểm tra hệ thống thủy lực và bảo quản máy nông cơ sau mùa vụ.',
    content: 'Sau mỗi mùa thu hoạch, việc bảo dưỡng máy nông nghiệp là yếu tố then chốt để máy hoạt động bền bỉ...',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    publishedAt: '2026-03-15',
    views: 980,
  },
];

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  companyName: 'Công ty TNHH Bảo Nam Tân Phú',
  slogan: 'Uy tín tạo nên thương hiệu',
  logoUrl: '',
  hotline: '0968 123 456',
  techSupportPhone: '0901 234 567',
  email: 'contact@nongcomachinery.vn',
  address: 'Hệ thống đại lý nông cơ toàn quốc',
  workingHours: '8:00 - 18:00 (Thứ 2 - Chủ Nhật)',
  warrantyPolicy: 'Bảo hành chính hãng 12-24 tháng',
  zaloPhone: '0968123456',
  heroTitleLine1: 'ĐỔI MỚI CÔNG NGHỆ',
  heroTitleLine2: 'NÂNG CAO NĂNG SUẤT NÔNG SẢN',
  heroDescription: 'Hệ thống máy gặt đập, máy xới đất và thiết bị nông cơ thế hệ mới chính hãng 100%.',
  aboutText: 'Nông Cơ Machinery là thương hiệu nhập khẩu và phân phối máy nông nghiệp, thiết bị cơ giới nông nghiệp hàng đầu tại Việt Nam. Chúng tôi cam kết mang tới cho bà con nông dân những giải pháp thiết bị hiện đại, bền bỉ, tiết kiệm nhiên liệu với chi phí tối ưu nhất.',
  facebookUrl: 'https://facebook.com',
  youtubeUrl: 'https://youtube.com',
  mapEmbedUrl: '',
  adminPassword: '', // MUST be set via ADMIN_PASSWORD env var — no hardcoded default
  bankAccountInfo: 'MB Bank - STK: 0968123456 - CTTNHH Nông Cơ Machinery',
  footerCopyright: '© 2026 NÔNG CƠ MACHINERY. Tất cả quyền được bảo lưu.',
  isWholesaleLockEnabled: true,
  wholesalePasscode: '', // MUST be set via settings or env — blank disables wholesale lock
  wholesaleNoticeText: 'Trang web dành riêng cho Đại Lý & Khách Hàng Sỉ. Vui lòng nhập Mã Truy Cập để xem Báo Giá & Danh Mục Sản Phẩm.',
  supabaseUrl: '', // MUST be set via SUPABASE_URL env var
  supabaseAnonKey: '', // MUST be set via SUPABASE_ANON_KEY env var
  isSupabaseStorageEnabled: false,
  isMarqueeEnabled: true,
  marqueeText: '🔥 KHUYẾN MÃI ĐẶC BIỆT: HỖ TRỢ TRẢ GÓP 0% LÃI SUẤT KHI MUA MÁY GẶT ĐẬP KUBOTA & YANMAR THÁNG NÀY! 🚜 BẢO HÀNH CHÍNH HÃNG 24 THÁNG - GIAO HÀNG TẬN NƠI TOÀN QUỐC! 📞 HOTLINE BÁO GIÁ SỈ: 0968 123 456',
};
